-- Creating the appointment table
CREATE TABLE appointment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- For H2
    appointment_time TIMESTAMP,
    doctor_id BIGINT,
    patient_name VARCHAR(255)
);

-- Inserting data into the appointment table
INSERT INTO appointment (id, doctor_id, patient_name, appointment_time)
VALUES (1, 1, 'Rajesh', '2025-06-10T10:00:00');

INSERT INTO appointment (id, doctor_id, patient_name, appointment_time)
VALUES (2, 2, 'Meena', '2025-06-11T14:30:00');

INSERT INTO appointment (id, doctor_id, patient_name, appointment_time)
VALUES (3, 3, 'Vikram', '2025-06-12T09:15:00');


-- *************************************************************************
-- FIX: Explicitly advance the H2 IDENTITY sequence
-- This tells H2 that the next generated ID should be MAX(id) + 1
-- *************************************************************************
ALTER TABLE appointment ALTER COLUMN id RESTART WITH (SELECT MAX(id) + 1 FROM appointment);